"""Postgres / 信创 DAL 方言翻译与（可选）真连测试。

纯翻译测试（_translate_sqlite_to_pg / _pg_sql）不依赖数据库，始终运行，锁定：
  - SQLite 自增主键 -> PG IDENTITY
  - INSERT OR IGNORE -> ON CONFLICT DO NOTHING（按表主键）
  - SQLite 路径原样不动（默认演示库不受影响）

真连测试（test_*_live_*）仅在环境变量 TELEOPS_TEST_PG_DSN 指向可达的 Postgres 时运行，
否则自动 skip——CI/本机无 PG 时零红。
"""
import os

import pytest

from src.core import db


# ---------------- 纯翻译单测（不依赖 DB） ----------------
def test_translate_autoincrement_to_identity():
    sql = "id INTEGER PRIMARY KEY AUTOINCREMENT,"
    out = db._translate_sqlite_to_pg(sql)
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "AUTOINCREMENT" not in out


def test_translate_insert_or_ignore_single_pk():
    sql = "INSERT OR IGNORE INTO workspaces (id,name) VALUES (?,?)"
    out = db._translate_sqlite_to_pg(sql)
    assert "ON CONFLICT (id) DO NOTHING" in out
    assert "OR IGNORE" not in out
    assert "VALUES (?,?)" in out   # 占位符归一由 _ph/_pg_sql 负责，这里只验结构转换


def test_translate_insert_or_ignore_composite_pk():
    sql = "INSERT OR IGNORE INTO role_permissions (role_id,permission) VALUES (?,?)"
    out = db._translate_sqlite_to_pg(sql)
    assert "ON CONFLICT (role_id, permission) DO NOTHING" in out


def test_pg_sql_returns_unchanged_for_sqlite(monkeypatch):
    # 强制 sqlite 协议，确保默认路径不做任何翻译
    monkeypatch.setattr(db, "DB_DSN", "sqlite:///tmp/foo.db")
    sql = "INSERT OR IGNORE INTO workspaces (id) VALUES (?)"
    assert db._pg_sql(sql) == sql


def test_pg_sql_translates_for_postgres_scheme(monkeypatch):
    monkeypatch.setattr(db, "DB_DSN", "postgresql://u:p@h:5432/db")
    sql = "INSERT OR IGNORE INTO tools (name) VALUES (?)"
    out = db._pg_sql(sql)
    assert "ON CONFLICT (name) DO NOTHING" in out
    assert "VALUES (%s)" in out


# ---------------- 真连测试（有 PG 才跑） ----------------
_PG_DSN = os.environ.get("TELEOPS_TEST_PG_DSN")


def _have_pg():
    if not _PG_DSN:
        return False
    try:
        import psycopg  # noqa: F401
        conn = psycopg.connect(_PG_DSN, connect_timeout=3)
        conn.close()
        return True
    except Exception:
        return False


@pytest.fixture(scope="module")
def pg_conn():
    import psycopg
    conn = psycopg.connect(_PG_DSN)
    # 用独立临时 schema，避免污染
    yield conn
    conn.close()


@pytest.mark.skipif(not _have_pg(), reason="无可达 Postgres（设 TELEOPS_TEST_PG_DSN 开启）")
def test_pg_schema_and_crud(pg_conn):
    """在真实 Postgres 上建表 + 插查 + 冲突忽略，证明 DAL 真连可用。"""
    orig_dsn = db.DB_DSN
    orig_conn = db._conn
    # 指向测试 DSN 并清掉缓存连接
    db.DB_DSN = _PG_DSN
    db._conn = None
    try:
        db._init_schema()
        db.execute("INSERT INTO users (username,password_hash,is_admin) VALUES (%s,%s,0)",
                   ("pg_test", "x"))
        # 自增 id 自动生成
        u = db.query_one("SELECT id, username FROM users WHERE username=%s", ("pg_test",))
        assert u["username"] == "pg_test"
        # INSERT OR IGNORE -> ON CONFLICT：重复插入应被忽略而非报错
        db.execute("INSERT OR IGNORE INTO users (username,password_hash,is_admin) VALUES (%s,%s,0)",
                   ("pg_test", "x"))
        cnt = db.query_one("SELECT COUNT(*) AS c FROM users WHERE username=%s", ("pg_test",))["c"]
        assert cnt == 1
        # 清理
        db.execute("DELETE FROM users WHERE username=%s", ("pg_test",))
    finally:
        db._conn = orig_conn
        db.DB_DSN = orig_dsn
