"""TeleOps 持久化层（DAL，数据访问层）。

Phase 1 改造：从「裸 sqlite3 直连」升级为 **可切换数据源的 DAL**，
为后续接入信创库（达梦/人大金仓）/ PostgreSQL 主从预留单一切换点
（环境变量 ``TELEOPS_DB_DSN``），同时保持当前演示默认跑在 SQLite 上。

设计要点：
- 连接工厂按 DSN 协议选择驱动；SQLite 走标准库零依赖，信创/PG 走懒加载
  （沙箱未装对应驱动时给出明确安装指引，不会静默跑错库）。
- SQL 写法保持**方言中立**（只用标准 SELECT/INSERT/UPDATE/DELETE + ``?`` 占位符，
  非 SQLite 协议自动转 ``%s``），避免 SQLite 独有语法，便于平滑切换。
- 多租户从「个人域（owner_id）」升级为「组织树 + RBAC」：
  * org_units：组织节点树（parent_id + 物化 path，任意深度，避免递归 CTE）
  * roles / role_permissions / user_roles：标准 RBAC（角色→权限，用户绑角色）
  * users / workspaces 增加 org_id，可见性按「本人 org 及其子孙 org」收纳
- 既有个人域（owner_id）判定保留，作为组织树之下的补充隔离维度。
- 所有写走 execute()，读走 query()/query_one()，均在锁内完成；WAL 提升并发。
"""
import importlib
import json
import os
import re
import sqlite3
import threading
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from src.config import DATA_DIR

# ---------------- DSN / 驱动切换点（信创预留） ----------------
# 优先级：TELEOPS_DB_FILE（测试隔离用的单文件 SQLite）> TELEOPS_DB_DSN（信创/PG 切换点）>
#         默认 data/teleops.db。
# 信创/PG 形如：
#   dm://user:pass@host:5236/dbname
#   kingbase://user:pass@host:54321/dbname
#   postgresql://user:pass@host:5432/dbname
# 切换时只需改 TELEOPS_DB_DSN + 在部署环境 pip install 对应驱动。
_DB_FILE = os.environ.get("TELEOPS_DB_FILE")
if _DB_FILE:
    DB_DSN = "sqlite://" + _DB_FILE
else:
    DB_DSN = os.environ.get("TELEOPS_DB_DSN") or f"sqlite://{DATA_DIR / 'teleops.db'}"

# 非 SQLite 协议 → 需要的 Python 驱动模块（懒加载，装了才连）
_DRIVER_MODULES = {
    "dm": "dmPython",
    "kingbase": "kingbase",
    "postgresql": "psycopg",
    "postgres": "psycopg",
}
# 这些协议使用 %s 占位符（SQLite/达梦/金仓用 ?）
_PCTS_PLACEHOLDER_SCHEMES = {"postgresql", "postgres", "dm", "kingbase"}


def _parse_dsn():
    if "://" not in DB_DSN:
        return "sqlite", DB_DSN  # 裸路径视为 sqlite 文件
    scheme, rest = DB_DSN.split("://", 1)
    return scheme.lower(), rest


def _ph(sql: str) -> str:
    """占位符方言归一：PG/达梦/金仓用 %s，其余（含 SQLite）保持 ?。"""
    scheme, _ = _parse_dsn()
    if scheme in _PCTS_PLACEHOLDER_SCHEMES:
        return sql.replace("?", "%s")
    return sql


# ---------------- SQLite -> PG/信创 方言翻译（DDL / 写语句） ----------------
# 非 SQLite 协议（PG/达梦/金仓）的少数 SQLite 专属语法需要翻译，避免直连时报语法错。
# 仅当 DSN 为非 SQLite 协议时调用，SQLite 路径完全不受影响。
_PK_COLS = {
    # 表 -> 主键列（用于把 SQLite 的 INSERT OR IGNORE 翻成 ON CONFLICT DO NOTHING）
    "workspaces": ["id"], "agents": ["id"], "requirements": ["id"],
    "tools": ["name"], "messages": ["id"],
    "role_permissions": ["role_id", "permission"], "user_roles": ["user_id", "role_id"],
    "users": ["id"], "audit_log": ["id"],
}


def _translate_sqlite_to_pg(sql: str) -> str:
    """把 SQLite 专属 DDL / 写语句翻译为 PG/信创兼容写法。

    - ``INTEGER PRIMARY KEY AUTOINCREMENT`` / ``INTEGER PRIMARY KEY`` -> 自增主键
      （PG 用 GENERATED BY DEFAULT AS IDENTITY；达梦/金仓语法接近，统一按 PG 形态）。
    - ``INSERT OR IGNORE INTO <tbl> ...`` -> ``INSERT INTO <tbl> ... ON CONFLICT (<pk>) DO NOTHING``。
    """
    s = sql
    s = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
               "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", s, flags=re.I)
    s = re.sub(r"INTEGER\s+PRIMARY\s+KEY\b",
               "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", s, flags=re.I)
    m = re.search(r"INSERT\s+OR\s+IGNORE\s+INTO\s+([A-Za-z_]+)", s, flags=re.I)
    if m:
        tbl = m.group(1)
        pk = _PK_COLS.get(tbl)
        s = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", s, flags=re.I)
        if pk:
            s = s.rstrip(";") + f" ON CONFLICT ({', '.join(pk)}) DO NOTHING"
    return s


def _pg_sql(sql: str) -> str:
    """按协议返回最终要执行的 SQL：非 SQLite 协议先翻方言再归一占位符；SQLite 原样。"""
    scheme, _ = _parse_dsn()
    if scheme in _PCTS_PLACEHOLDER_SCHEMES:
        return _translate_sqlite_to_pg(_ph(sql))
    return sql


# 数据库文件 / 连接
_LOCK = threading.Lock()
_conn = None

# RBAC 权限全集
PERMISSIONS = [
    "ws.view",      # 查看业务域 / Agent
    "ws.manage",    # 创建/编辑/删除业务域、改模式
    "agent.manage", # 域内增删改 Agent
    "alert.ack",    # 确认/处置告警、启动告警流
    "tool.exec",    # 执行/造运维工具（含高危需审批）
    "audit.view",   # 查看操作审计
    "org.manage",   # 管理组织节点、成员、角色
]
PERMISSION_SET = set(PERMISSIONS)

# 内置角色 → 权限
BUILTIN_ROLES = {
    "super_admin": list(PERMISSIONS),                       # 全部权限
    "org_admin":   ["ws.view", "ws.manage", "agent.manage",
                    "alert.ack", "tool.exec", "audit.view", "org.manage"],
    "sre":         ["ws.view", "agent.manage", "alert.ack", "tool.exec"],
    "dev":         ["ws.view", "agent.manage"],
    "viewer":      ["ws.view", "audit.view"],
}
ROOT_ORG_ID = "grp-root"


_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  is_admin INTEGER DEFAULT 0,
  org_id TEXT,
  created_at TEXT
);
CREATE TABLE IF NOT EXISTS org_units (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  parent_id TEXT,
  path TEXT NOT NULL,
  level INTEGER DEFAULT 0,
  org_type TEXT DEFAULT 'team'
);
CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  builtin INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id TEXT NOT NULL,
  permission TEXT NOT NULL,
  PRIMARY KEY(role_id, permission)
);
CREATE TABLE IF NOT EXISTS user_roles (
  user_id INTEGER NOT NULL,
  role_id TEXT NOT NULL,
  PRIMARY KEY(user_id, role_id)
);
CREATE TABLE IF NOT EXISTS workspaces (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  adapter_id TEXT,
  mode TEXT DEFAULT 'auto',
  owner_id INTEGER,
  org_id TEXT,
  created_at TEXT,
  FOREIGN KEY(owner_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS agents (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT '[]',
  description TEXT DEFAULT '',
  is_primary INTEGER DEFAULT 0,
  status TEXT DEFAULT 'idle',
  FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS requirements (
  id TEXT PRIMARY KEY,
  workspace_id TEXT,
  status TEXT DEFAULT 'pending',
  data TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT
);
CREATE TABLE IF NOT EXISTS tools (
  name TEXT PRIMARY KEY,
  executor TEXT,
  risk TEXT DEFAULT 'low',
  require_human_approval INTEGER DEFAULT 0,
  description TEXT DEFAULT '',
  workspace_id TEXT,
  created_at TEXT
);
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  agent_id TEXT,
  agent_name TEXT,
  kind TEXT,
  summary TEXT,
  detail TEXT,
  ts TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT NOT NULL,
  actor TEXT NOT NULL,
  actor_id INTEGER,
  action TEXT NOT NULL,
  workspace_id TEXT,
  detail TEXT,
  result TEXT DEFAULT 'ok',
  ip TEXT
);
"""


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def _raw_connect():
    """按 DSN 选择驱动并建立连接（缓存于模块级 _conn）。"""
    global _conn
    scheme, target = _parse_dsn()
    if scheme == "sqlite":
        _conn = sqlite3.connect(target, check_same_thread=False, timeout=5.0)
        _conn.row_factory = sqlite3.Row
        _conn.execute("PRAGMA foreign_keys = ON")
        _conn.execute("PRAGMA journal_mode = WAL")
        _conn.execute("PRAGMA synchronous = NORMAL")
        _conn.execute("PRAGMA busy_timeout = 5000")
        return _conn
    # ---- 信创 / PostgreSQL 切换点 ----
    mod = _DRIVER_MODULES.get(scheme)
    if not mod:
        raise RuntimeError(
            f"不支持的数据库协议 '{scheme}'（DSN={DB_DSN}）。"
            f"当前支持的协议：sqlite / dm / kingbase / postgresql。")
    try:
        driver = importlib.import_module(mod)
    except ImportError as e:
        raise RuntimeError(
            f"未安装 '{scheme}' 数据库驱动（需模块 {mod}），无法连接 {DB_DSN}。\n"
            f"请在部署环境执行：pip install {mod}\n"
            f"（当前开发/演示默认使用 SQLite，设置 TELEOPS_DB_DSN=sqlite://<路径> 即可）"
        ) from e
    # 达梦/金仓/PG 的 connect 接口基本一致（传 DSN 字符串）
    _conn = driver.connect(target)
    # PG（psycopg）结果行设为 dict，统一走 _row_to_dict；其余驱动保持默认
    if driver.__name__ == "psycopg":
        try:
            import psycopg
            _conn.row_factory = psycopg.rows.dict_row
        except Exception:
            pass
    return _conn


def get_conn() -> object:
    """惰性创建并缓存全局连接（线程安全）。首次连接建表 + 迁移 + 播种 RBAC。"""
    global _conn
    if _conn is None:
        _raw_connect()
        _init_schema()
        _migrate_columns()
        _migrate_from_json()
        _seed_rbac()
    return _conn


def _init_schema():
    scheme, _ = _parse_dsn()
    if scheme == "sqlite":
        get_conn().executescript(_SCHEMA)
        get_conn().commit()
        return
    # PG/达梦/金仓：executescript 不可用，按 ; 拆成单条 DDL 并翻方言后逐条执行
    conn = get_conn()
    for stmt in _SCHEMA.split(";"):
        sql = _pg_sql(stmt.strip())
        if not sql:
            continue
        conn.execute(sql)
    conn.commit()


def _migrate_columns():
    """为既有库补齐新列（org_id），幂等。"""
    for col, table in (("org_id", "users"), ("org_id", "workspaces")):
        try:
            get_conn().execute(f"ALTER TABLE {table} ADD COLUMN {col} TEXT")
            get_conn().commit()
        except Exception:
            pass  # 列已存在则忽略


def _migrate_from_json():
    """仅在 workspaces 表为空且遗留 JSON 存在时迁移一次。"""
    if get_conn().execute("SELECT COUNT(*) FROM workspaces").fetchone()[0] > 0:
        return
    # 业务域 + Agent
    wf = DATA_DIR / "workspaces.json"
    if wf.exists():
        try:
            data = json.loads(wf.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for w in data.get("workspaces", []):
            get_conn().execute(
                "INSERT OR IGNORE INTO workspaces (id,name,adapter_id,mode,owner_id,created_at) "
                "VALUES (?,?,?,?,?,?)",
                (w["id"], w["name"], w.get("adapter_id"), w.get("mode", "auto"),
                 None, _now()))
            for a in w.get("agents", []):
                get_conn().execute(
                    "INSERT OR IGNORE INTO agents "
                    "(id,workspace_id,name,kind,scope,description,is_primary,status) "
                    "VALUES (?,?,?,?,?,?,?,?)",
                    (a["id"], w["id"], a["name"], a["kind"],
                     json.dumps(a.get("scope", []), ensure_ascii=False),
                     a.get("description", ""), 1 if a.get("primary") else 0,
                     a.get("status", "idle")))
    # 需求
    rf = DATA_DIR / "requirements.json"
    if rf.exists():
        try:
            data = json.loads(rf.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for r in data.get("requirements", []):
            get_conn().execute(
                "INSERT OR IGNORE INTO requirements "
                "(id,workspace_id,status,data,created_at,updated_at) VALUES (?,?,?,?,?,?)",
                (r.get("id"), r.get("workspace_id"), r.get("status", "pending"),
                 json.dumps(r, ensure_ascii=False), r.get("created_at"), r.get("updated_at")))
    # 工具
    tf = DATA_DIR / "tools.json"
    if tf.exists():
        try:
            data = json.loads(tf.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for t in data.get("tools", []):
            get_conn().execute(
                "INSERT OR IGNORE INTO tools "
                "(name,executor,risk,require_human_approval,description,workspace_id,created_at) "
                "VALUES (?,?,?,?,?,?,?)",
                (t.get("name"), t.get("executor"), t.get("risk", "low"),
                 1 if t.get("require_human_approval") else 0,
                 t.get("description", ""), t.get("workspace_id"), _now()))
    # 操作记录
    mf = DATA_DIR / "messages.json"
    if mf.exists():
        try:
            data = json.loads(mf.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for ws_id, msgs in data.get("messages", {}).items():
            for m in msgs:
                get_conn().execute(
                    "INSERT OR IGNORE INTO messages "
                    "(id,workspace_id,agent_id,agent_name,kind,summary,detail,ts) VALUES (?,?,?,?,?,?,?,?)",
                    (m.get("id"), ws_id, m.get("agent_id"), m.get("agent_name"),
                     m.get("kind"), m.get("summary"), m.get("detail"), m.get("ts")))
    get_conn().commit()


# ---------------- RBAC 播种（幂等） ----------------
def _seed_rbac():
    """播根组织 + 内置角色 + 为既有用户指派组织/角色（向后兼容）。

    - 根组织 grp-root（集团总部）。
    - 5 个内置角色及其权限。
    - 既有 users.org_id 为空 → 归入根组织；is_admin 者授 super_admin，否则授 sre。
    - 新用户由 auth.create_user 自行建个人组织叶节点并授角色。
    """
    if not query_one("SELECT 1 FROM org_units WHERE id=?", (ROOT_ORG_ID,)):
        execute("INSERT INTO org_units (id,name,parent_id,path,level,org_type) "
                "VALUES (?,?,?,?,?,?)",
                (ROOT_ORG_ID, "集团总部", None, "/" + ROOT_ORG_ID, 0, "group"))
    for rid, perms in BUILTIN_ROLES.items():
        if not query_one("SELECT 1 FROM roles WHERE id=?", (rid,)):
            execute("INSERT INTO roles (id,name,builtin) VALUES (?,?,1)", (rid, rid))
        for p in perms:
            execute("INSERT OR IGNORE INTO role_permissions (role_id,permission) VALUES (?,?)",
                    (rid, p))
    # 既有用户补齐组织 + 角色
    for u in query("SELECT * FROM users"):
        if not u["org_id"]:
            execute("UPDATE users SET org_id=? WHERE id=?", (ROOT_ORG_ID, u["id"]))
        rid = "super_admin" if u["is_admin"] else "sre"
        execute("INSERT OR IGNORE INTO user_roles (user_id,role_id) VALUES (?,?)",
                (u["id"], rid))


def org_path_of(org_id: str) -> Optional[str]:
    """返回组织物化路径（用于子树包含判定）；不存在返回 None。"""
    r = query_one("SELECT path FROM org_units WHERE id=?", (org_id,))
    return r["path"] if r else None


# ---------------- 通用封装（线程安全 + 方言中立） ----------------
def execute(sql: str, params=()):
    """执行写操作并提交，返回 cursor（调用方可用 rowcount 判断影响行数）。

    注意：``get_conn()`` 必须在加锁**之前**调用。首次调用会触发建表/迁移/播种，
    而播种内部又会回调用 ``execute/query``——若 get_conn 在锁内，会因非重入锁
    造成递归死锁。把初始化放在锁外即可解开。
    """
    conn = get_conn()
    with _LOCK:
        cur = conn.execute(_pg_sql(sql), params)
        conn.commit()
    return cur


def query(sql: str, params=()):
    conn = get_conn()
    with _LOCK:
        rows = conn.execute(_pg_sql(sql), params).fetchall()
    # PG 驱动返回的不是 sqlite.Row，统一转 dict 方便上层访问
    return [_row_to_dict(r) for r in rows]


def query_one(sql: str, params=()):
    conn = get_conn()
    with _LOCK:
        row = conn.execute(_pg_sql(sql), params).fetchone()
    return _row_to_dict(row) if row is not None else None


def _row_to_dict(row):
    if isinstance(row, dict):
        return row
    try:
        return {k: row[k] for k in row.keys()}
    except Exception:
        return dict(row)


# ---------------- 操作审计（多租户问责） ----------------
def audit(actor, action, workspace_id=None, detail=None, result="ok",
          actor_id=None, ip=None):
    """写入一条操作审计记录。任何异常都静默吞掉，绝不阻断主流程。

    actor：操作人（用户名 / 'anonymous' / 'system'）
    action：动作标识（如 auth.login / workspace.create / agent.delete / stream.start /
            tool.build 等）
    workspace_id：受影响的业务域（可空，如登录类动作）
    detail：人类可读摘要，或结构化 dict（自动 JSON 化）
    result：'ok' / 'denied' / 'error'
    actor_id / ip：可选，便于回溯具体账号与来源
    """
    try:
        if detail is not None and not isinstance(detail, str):
            detail = json.dumps(detail, ensure_ascii=False)
        conn = get_conn()
        with _LOCK:
            conn.execute(
                "INSERT INTO audit_log "
                "(ts,actor,actor_id,action,workspace_id,detail,result,ip) "
                "VALUES (?,?,?,?,?,?,?,?)",
                (_now(), str(actor), actor_id, action, workspace_id, detail,
                 result, ip))
            conn.commit()
    except Exception as e:  # 审计失败绝不影响主业务
        print(f"[warn] audit log write failed: {e}")


def audit_rows(limit=50, offset=0, workspace_id=None, actor_id=None):
    """按条件倒序读取审计记录（最新在前）。供 GET /audit 使用。"""
    clauses, params = [], []
    if workspace_id is not None:
        clauses.append("workspace_id=?")
        params.append(workspace_id)
    if actor_id is not None:
        clauses.append("actor_id=?")
        params.append(actor_id)
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    rows = query(
        f"SELECT * FROM audit_log {where} ORDER BY id DESC LIMIT ? OFFSET ?",
        tuple(params) + (limit, offset))
    total = query_one(
        f"SELECT COUNT(*) AS c FROM audit_log {where}", tuple(params))["c"]
    return rows, total
